---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: firewalld
  vars:
    firewalld_enabled: true
    firewalld_ports_list:
      - port: 666/tcp
    firewalld_reboot_machine: false
