---
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/geerlingguy/docker-fedora40-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: default
  test_sequence:
    - create
    - converge
    - idempotence
    - verify
    - destroy
verifier:
  name: testinfra
