---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: packages
  vars:
    packages_skip_upgrade: false
    packages_list:
      - name: vim
        present: false
      - name: git
