---
driver:
  name: podman

platforms:
  - name: packages.fedora42
    image: docker.io/geerlingguy/docker-fedora42-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

  - name: packages.ubuntu2404
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  playbooks:
    converge: converge.yml

scenario:
  name: default
  test_sequence:
    - create
    - converge
    - destroy
