---
- name: Manage cockpit package
  ansible.builtin.package:
    name: cockpit
    state: "{{ cockpit_destroy | ternary('absent', 'present') }}"
    update_cache: true
  become: true

- name: Start and enable cockpit
  ansible.builtin.service:
    name: cockpit
    state: started
    enabled: true
  become: true

- name: Manage directory for the certificates
  ansible.builtin.file:
    path: "{{ cockpit_cert_dir }}"
    state: "{{ cockpit_destroy | ternary('absent', 'directory') }}"
    mode: "0644"
  become: true

- name: Create certificates
  when:
    - not cockpit_destroy
    - not cockpit_cert_key is none
    - not cockpit_cert_crt is none
  ansible.builtin.copy:
    content: "{{ item.content }}"
    dest: "{{ cockpit_cert_dir }}/{{ item.dest }}"
    mode: "0644"
  loop:
    - content: "{{ cockpit_cert_key }}"
      dest: cert.key
    - content: "{{ cockpit_cert_crt }}"
      dest: cert.crt
  become: true
