---
- name: Manage cockpit service
  when: not cockpit_package_present
  ansible.builtin.systemd:
    name: cockpit
    state: "{{ cockpit_service_enabled | ternary('started', 'stopped') }}"
    enabled: "{{ cockpit_service_enabled }}"
    masked: "{{ not cockpit_service_enabled }}"
  become: true

- name: Absent motd cockpit
  when: cockpit_motd_absent
  ansible.builtin.file:
    name: /etc/motd.d/cockpit
    state: absent
