---
namespace: dda104
name: linux_base
version: 1.12.8
readme: README.md
authors:
  - Denis Dvornikov
description: Collection for managing Linux systems
license:
  - Unlicense
repository: https://gitlab.com/dda104/linux_base
