---
namespace: dda104
name: linux_base
version: 1.4.4
readme: README.md
authors:
  - Denis Dvornikov
description: This collection offers a set of roles for managing Linux systems
license:
  - Unlicense
tags:
  - linux
  - linux_base
  - users
  - packages
  - cockpit
  - firewalld
  - hostname
  - selinux
  - nmcli
  - authentificator
dependencies: {}
repository: https://gitlab.com/ansible_public/dda104.linux_base
