---
argument_specs:
  main:
    options:
      firewalld_enabled:
        type: bool

      firewalld_reboot_machine:
        type: bool

      firewalld_reload:
        type: bool

      firewalld_reload_zones:
        type: bool

      firewalld_zones:
        type: list
        elements: dict
        options:
          name:
            type: str

          target:
            type: str
            choices:
              - default
              - ACCEPT
              - DROP
              - REJECT

          present:
            type: bool

          permanent:
            type: bool

          ports:
            type: list
            elements: dict
            required: true
            options:
              name:
                type: str

              present:
                type: bool

              permanent:
                type: bool

          services:
            type: list
            elements: dict
            required: true
            options:
              name:
                type: str

              present:
                type: bool

              permanent:
                type: bool

          rich_rules:
            type: list
            elements: dict
            required: true
            options:
              name:
                type: str

              present:
                type: bool

              permanent:
                type: bool

          interfaces:
            type: list
            elements: dict
            required: true
            options:
              name:
                type: str

              present:
                type: bool

              permanent:
                type: bool

              switch_zone:
                type: bool
