---
argument_specs:
  main:
    short_description: Role for configure firewalld
    version_added: 1.0.0
    author: Denis Dvornikov
    options:
      firewalld_enabled:
        description: Whether firewalld should be enabled
        type: bool
        default: false
      firewalld_ports_list:
        description: List of ports to manage
        type: list
        elements: dict
        default: []
        options:
          port:
            description: Port number
            type: str
          permanent:
            description: Whether the rule should be permanent
            type: bool
            default: true
          state:
            description: The state of the rule (present/absent)
            type: str
            choices:
              - enabled
              - disabled
            default: enabled
      firewalld_reboot_machine:
        description: Reboot machine on handler
        type: bool
        default: true
