---
dependencies:
  - role: dda104.linux_base.packages
    vars:
      packages_list:
        - name: firewalld

galaxy_info:
  role_name: firewalld
  description: Role for configure firewalld
  company: ""
  namespace: internal
  license: Unlicense
  min_ansible_version: "2.11"
  author: Denis Dvornikov
  galaxy_tags:
    - linux
    - firewalld
