---
- name: Manage packages
  when: |
    packages_list | length or
    not packages_skip_upgrade
  ansible.builtin.include_tasks: package.yml

- name: Manage snap packages
  when: packages_snap_list | length
  ansible.builtin.include_tasks: snap.yml
