---
- name: Upgrade all packages
  become: true
  when: not packages_skip_upgrade
  ansible.builtin.package:
    name: "*"
    state: latest
    update_cache: true
  tags:
    - skip_ansible_lint

- name: Manage packages
  become: true
  ansible.builtin.package:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
  with_items: "{{ packages_list }}"

- name: Manage snap packages
  community.general.snap:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
    classic: "{{ item.classic | default(omit) }}"
  with_items: "{{ packages_snap_list }}"
