---
- name: Manage packages
  become: true
  block:
    - name: Install dnf requirements
      when: |
        ansible_pkg_mgr == "dnf5" or
        ansible_pkg_mgr == "dnf"
      block:
        - name: Install dnf requirements
          ansible.builtin.raw: |
            dnf in python3-libdnf5 -y
          register: _packages_libdnf5
          changed_when: '"Nothing to do." not in _packages_libdnf5.stdout'

        - name: Install python3-rpm
          ansible.builtin.package:
            name: python3-rpm
            state: present

    - name: Manage packages
      ansible.builtin.package:
        name: "{{ item.name }}"
        state: "{{ item.present | d(true) | ternary('present', 'absent') }}"
        update_cache: "{{ item.update_cache | d(true) }}"
        disable_gpg_check: "{{ item.disable_gpg_check | d(true if item.name is match('https://.*') else omit) }}"
      with_items: "{{ packages_list }}"

    - name: Upgrade all packages
      when: not packages_skip_upgrade
      ansible.builtin.package:
        name: "*"
        state: latest
        update_cache: true
        update_only: true
      register: _packages_upgrade_all
      changed_when: '"Nothing to do" not in _packages_upgrade_all.msg'
