---
dependencies: []

galaxy_info:
  role_name: asdf
  description: Role for install asdf
  company: ""
  namespace: internal
  license: Unlicense
  min_ansible_version: "2.11"
  author: Denis Dvornikov
  galaxy_tags:
    - linux
    - packages
