---
driver:
  name: podman
platforms:
  - name: fedora
    image: docker.io/geerlingguy/docker-fedora40-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
  - name: ubuntu
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  playbooks:
    converge: converge.yml
scenario:
  name: destroy
  test_sequence:
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - destroy
