---
driver:
  name: podman

platforms:
  - name: pre_ansible.fedora41.molecule
    image: docker.io/geerlingguy/docker-fedora41-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

  - name: pre_ansible.ubuntu2404.molecule
    image: docker.io/geerlingguy/docker-ubuntu2404-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
  playbooks:
    converge: converge.yml

scenario:
  name: default
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: testinfra
