---
dependencies: []

galaxy_info:
  role_name: pre_ansible
  description: Role for prepare Linux systems
  company: ""
  namespace: internal
  license: Unlicense
  min_ansible_version: "2.11"
  author: Denis Dvornikov
  galaxy_tags:
    - linux
