---
argument_specs:
  main:
    options:
      users_list:
        type: list
        elements: dict
        options:
          name:
            type: str
            required: true

          password:
            type: str

          present:
            type: bool

          uid:
            type: int

          sudo:
            type: bool
