---
dependencies: []

galaxy_info:
  role_name: users
  description: Role for manage users
  company: ""
  namespace: internal
  license: Unlicense
  min_ansible_version: "2.11"
  author: Denis Dvornikov
  galaxy_tags:
    - linux
    - users
