---
argument_specs:
  main:
    short_description: Role for configure firewalld
    version_added: 1.0.0
    author: Denis Dvornikov
    options:
      cockpit_cert_dir:
        description: Directory for cockpit certificates
        type: str
        default: /etc/cockpit/ws-certs.d
      cockpit_cert_key:
        description: Path to the key file
        type: str
        default: null
      cockpit_cert_crt:
        description: Path to the crt file
        type: str
        default: null
