---
dependencies:
  - role: dda104.linux_base.packages
    vars:
      packages_list:
        - name: cockpit
          state: "{{ cockpit_package_present | ternary('present', 'absent') }}"

galaxy_info:
  description: Role for manage cockpit
  license: Unlicense
  min_ansible_version: "2.11"
  author: Denis Dvornikov
