---
driver:
  name: podman

platforms:
  - name: firewalld.fedora41.molecule
    image: docker.io/geerlingguy/docker-fedora41-ansible:latest
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    command: /usr/sbin/init
    privileged: true
    pre_build_image: true

provisioner:
  name: ansible
  config_options:
    defaults:
      result_format: yaml
      callbacks_enabled: profile_tasks
      gathering: "smart"
      fact_caching: jsonfile
      fact_caching_connection: "./.facts"
      fact_caching_timeout: 86400
      forks: 20
  env:
    ANSIBLE_ROLES_PATH: "../../../"
    ANSIBLE_PIPELINING: true
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: disable
  test_sequence:
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - destroy

verifier:
  name: ansible
