---
- name: Manage users
  become: true
  block:
    - name: Create and delete users
      ansible.builtin.user:
        name: "{{ item.name }}"
        password: "{{ item.password | d(omit) }}"
        state: "{{ item.present | d(true) | ternary('enabled', 'disabled') }}"
        uid: "{{ item.uid | d(omit) }}"
      loop: "{{ users_list }}"

    - name: Add user sudo
      when:
        - item.sudo | d(false)
        - item.present | d(true)
      ansible.builtin.copy:
        content: "{{ item.name }} ALL=(ALL) NOPASSWD:ALL"
        dest: "/etc/sudoers.d/{{ item.name }}"
        mode: "0440"
      loop: "{{ users_list }}"

    - name: Remove user sudo
      when: |
        not item.sudo | d(false) or
        not item.present
      ansible.builtin.file:
        dest: "/etc/sudoers.d/{{ item.name }}"
        state: absent
      loop: "{{ users_list }}"
