---
firewalld_enabled: true
firewalld_reboot_machine: false

firewalld_zones: []
# firewalld_zones:
#   - name: public
#     target: DROP
#     present: true
#     permanent: true
#     interfaces:
#       - name: "{{ ansible_default_ipv4.interface }}"
#         present: true
#         permanent: true
#     ports:
#       - name: 80/tcp
#         present: true
#         permanent: true
#       - name: 443/tcp
#         present: true
#         permanent: true
#     services:
#       - name: ssh
#         present: true
#         permanent: true
#     rich_rules:
#       - name: rule family=ipv4 source address=192.168.0.50/32 service name="ssh" accept
#         present: true
#         permanent: true
