---
- name: Configure firewalld
  become: true
  block:
    - name: Manage firewalld service
      ansible.builtin.service:
        name: firewalld
        state: "{{ firewalld_enabled | ternary('started', 'stopped') }}"
        enabled: "{{ firewalld_enabled }}"
      notify: Restart machine

    - name: Manage firewalld rules
      when: firewalld_enabled
      block:
        - name: Manage zones
          ansible.posix.firewalld:
            zone: "{{ item.name }}"
            target: "{{ item.target | default(omit) }}"
            state: "{{ item.present | default(true) | ternary('present', 'absent') }}"
            permanent: "{{ item.permanent | default(false) }}"
          with_items: "{{ firewalld_zones }}"

        - name: Manage interfaces
          ansible.posix.firewalld:
            interface: "{{ item.1.name }}"
            state: "{{ item.1.present | default(true) | ternary('enabled', 'disbled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | default(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - interfaces

        - name: Manage ports
          when: firewalld_enabled
          ansible.posix.firewalld:
            port: "{{ item.1.name }}"
            state: "{{ item.1.present | default(true) | ternary('enabled', 'disbled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | default(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - interfaces

        - name: Manage services
          when: firewalld_enabled
          ansible.posix.firewalld:
            service: "{{ item.1.name }}"
            state: "{{ item.1.present | default(true) | ternary('enabled', 'disbled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | default(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - services

        - name: Manage rich rules
          when: firewalld_enabled
          ansible.posix.firewalld:
            rich_rule: "{{ item.1.name }}"
            state: "{{ item.1.present | default(true) | ternary('enabled', 'disbled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | default(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - rich_rules
