---
- name: Configure firewalld
  become: true
  block:
    - name: Manage firewalld service
      ansible.builtin.service:
        name: firewalld
        state: "{{ firewalld_enabled | ternary('started', 'stopped') }}"
        enabled: "{{ firewalld_enabled }}"
      notify: Restart machine

    - name: Manage firewalld rules
      when: firewalld_enabled
      notify: Reload firewalld
      block:
        - name: Manage zones
          notify: Reload firewalld zones
          ansible.posix.firewalld:
            zone: "{{ item.name }}"
            state: "{{ item.present | d(true) | ternary('present', 'absent') }}"
            permanent: "{{ item.permanent | d(false) }}"
          with_items: "{{ firewalld_zones }}"

        - name: Flush handlers
          ansible.builtin.meta: flush_handlers

        - name: Manage zones target
          ansible.posix.firewalld:
            zone: "{{ item.name }}"
            target: "{{ item.target | d(omit) }}"
            state: "{{ item.present | d(true) | ternary('present', 'absent') }}"
            permanent: "{{ item.permanent | d(false) }}"
          with_items: "{{ firewalld_zones }}"

        - name: Manage ports
          when: item.1.name is defined
          ansible.posix.firewalld:
            port: "{{ item.1.name }}"
            state: "{{ item.1.present | d(true) | ternary('enabled', 'disabled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | d(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - ports

        - name: Manage services
          when: item.1.name is defined
          ansible.posix.firewalld:
            service: "{{ item.1.name }}"
            state: "{{ item.1.present | d(true) | ternary('enabled', 'disabled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | d(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - services

        - name: Manage rich rules
          when: item.1.name is defined
          ansible.posix.firewalld:
            rich_rule: "{{ item.1.name }}"
            state: "{{ item.1.present | d(true) | ternary('enabled', 'disabled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | d(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - rich_rules

        - name: Manage interfaces
          when: item.1.name is defined
          ansible.posix.firewalld:
            interface: "{{ item.1.name }}"
            state: "{{ item.1.present | d(true) | ternary('enabled', 'disabled') }}"
            zone: "{{ item.0.name }}"
            permanent: "{{ item.1.permanent | d(false) }}"
          with_subelements:
            - "{{ firewalld_zones }}"
            - interfaces

        - name: Flush handlers
          ansible.builtin.meta: flush_handlers

    - name: Switch interface zone
      when:
        - item.1.present
        - item.1.switch_zone
      community.general.nmcli:
        type: ethernet
        conn_name: "{{ item.1.name }}"
        zone: "{{ item.0.name }}"
        state: present
      with_subelements:
        - "{{ firewalld_zones }}"
        - interfaces
