---
- name: Reload firewalld
  when: firewalld_reload
  ansible.builtin.service:
    name: firewalld
    state: reloaded

- name: Switch interface zone
  when: item.1.present
  community.general.nmcli:
    type: ethernet
    conn_name: "{{ item.1.name }}"
    zone: "{{ item.0.name }}"
    state: present

- name: Restart machine
  when: firewalld_reboot_machine
  ansible.builtin.reboot:
    reboot_timeout: 300
