---
argument_specs:
  main:
    short_description: Role for installing and upgrading packages
    version_added: 1.0.0
    author: Denis Dvornikov
    options:
      packages_list:
        description: List of packages to install
        type: list
        elements: dict
        default: []
        options:
          name:
            description: Package name
            type: str
            required: true
          state:
            description: Package state
            type: str
            choices:
              - present
              - absent
            default: present
      packages_skip_upgrade:
        description: Upgrade all packages
        type: bool
        default: true
