---
- name: Converge
  hosts: all
  tasks:
    - name: Include role
      ansible.builtin.include_role:
        name: firewalld
  vars:
    firewalld_enabled: false
    firewalld_reboot_machine: false
